import "./globals.css";
import NavigationHeader from "./components/navigationHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavigationHeader/>
      </body>
    </html>
  );
}
